services:
  measurement:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "/package/experiments/measure.sh"]
    volumes:
      - ./package:/package
      - /lib/modules:/lib/modules
    privileged: true 
